### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Create a null vector of size 10

In [3]:
np.zeros((10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 3. Create a vector with values ranging from 10 to 49

In [5]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4. Find the shape of previous array in question 3

In [6]:
a.shape

(40,)

### 5. Print the type of the previous array in question 3

In [7]:
# type shows data type in python,dtype will show type in NumPy.
print(type(a)) 
print(a.dtype)

<class 'numpy.ndarray'>
int32


### 6. Print the numpy version and the configuration

In [9]:
print(np.version.version)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

### 7. Print the dimension of the array in question 3

In [10]:
print(a.ndim)

1


### 8. Create a boolean array with all the True values

In [14]:
#Method 1
true_arr = np.full((10,), True, dtype=bool)
print(true_arr)

#Method 2
arr = np.full((10,), 1)
true_arr = (arr == 1)
print(true_arr)

[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]


### 9. Create a two dimensional array

In [16]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### 10. Create a three dimensional array

In [24]:
a1=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
a1

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [27]:
#OR
x = 24
a2 = np.arange(0, x)
arr_3d = np.reshape(a2, (-1, int(x/3)))
arr_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

### 11. Reverse a vector (first element becomes last)

In [28]:
a=np.array([1,2,3,4,5])
print(a)
print(a[-1::-1])

[1 2 3 4 5]
[5 4 3 2 1]


### 12. Create a null vector of size 10 but the fifth value which is 1

In [29]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 13. Create a 3x3 identity matrix

In [31]:
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 14. Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


In [32]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])